[build]
  base = "frontend"
  publish = "frontend/dist/clockwrk/browser"
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

